// Nothing internal may reach a visitor.
//
// Three kinds of proof, because a replay is not one:
//
//   1. the real leaked reply, byte for byte, must be cleaned or discarded
//   2. a property test over state blocks generated by the real builders,
//      so this cannot drift as the blocks change wording
//   3. a structural check of the route source, so no future sink can read
//      the ungated reply
//
//   npx tsx scripts/test-reply-guard.ts

import { readFileSync } from "fs";
import { join } from "path";
import {
  INTERNAL_STATE_CLOSE,
  INTERNAL_STATE_OPEN,
  SAFE_FALLBACK,
  containsInternalState,
  stripInternalState,
} from "../lib/reply-guard";
import { buildConversationStateBlock, type ChatTurn } from "../lib/conversation-state";
import { buildMediaInstruction, type MediaDecision } from "../lib/chat-media";

let bad = 0;
const check = (name: string, ok: boolean, detail?: string) => {
  if (!ok) {
    bad++;
    console.log(`FAIL  ${name}`);
    if (detail) console.log(`        ${detail}`);
  } else {
    console.log(`  ok  ${name}`);
  }
};

// The reply an actual visitor received, reproduced from the stored row.
const LEAKED = `CONVERSATION STATE (computed, this turn only)

You have ALREADY made these offers in this conversation:
  • "Would you like to see a photo of the implant brands we work with, or some before and after results?"

Do not make any of these offers again. They have been heard. If the visitor wanted to take one up, they would have. Offer something different, or — more often the better choice — offer nothing and simply continue the conversation.

THIS REPLY CARRIES NO IMAGE, and none is being sent. That is information for you, not for the visitor: never say it to them, never mention what is or is not attached, and never explain how images work here.

You may OFFER to show the visitor these, and nothing else:
  • Before and after ( dental implants )
  • Crowns brand
  • Implants brand
An offer is a question, not a delivery. If they accept, the image is attached automatically to the reply you write next, and you will be told so in advance.

I need to show the implants brand photo and the before and after dental implants photo, but I can only attach one image per reply. I'll show the implants brand first, then before and after in the next reply.

The implants brand image is available and the visitor accepted. But the system says "THIS REPLY CARRIES NO IMAGE" — so I cannot show it this turn. I should not promise it's coming. I'll just continue the conversation naturally without mentioning images.

I'll acknowledge their interest and move the conversation forward naturally, covering another category.

With 15 years of experience behind us, we've handled countless full-mouth restorations — it's one of the areas we're most trusted for.

For a full mouth case like yours, the process runs across two visits: the first is 5 days, where the implants are placed and temporary teeth are fitted so you're never without a smile. Then after a 4-month healing period, you come back for 7 days and we fit the final zirconia crowns.

Are you based locally in Istanbul, or would you be traveling in for the treatment?`;

console.log("--- the real leak ---");
const cleanedLeak = stripInternalState(LEAKED);
check("the leaked reply is detected as contaminated", containsInternalState(LEAKED));
check("it is cleaned or discarded, never passed through", cleanedLeak !== LEAKED);
check(
  "nothing internal survives",
  cleanedLeak === null || !containsInternalState(cleanedLeak),
  cleanedLeak?.slice(0, 80)
);
check(
  "the genuine answer is what remains",
  cleanedLeak !== null && cleanedLeak.startsWith("With 15 years of experience"),
  cleanedLeak === null ? "discarded entirely" : cleanedLeak.slice(0, 60)
);
check(
  "the model's reasoning is gone",
  cleanedLeak !== null && !/I'll show the implants brand first|the system says/i.test(cleanedLeak)
);

console.log("\n--- shapes ---");
const REAL_REPLY =
  "We use Implant Swiss dental implants for their Swiss precision, and the results genuinely last. What matters most to you about the outcome?";

const shapes: [string, string, "clean" | "discard"][] = [
  ["state block alone leaves nothing to show", LEAKED.split("\n\nI need to show")[0], "discard"],
  ["fenced echo is caught", `${INTERNAL_STATE_OPEN}\nanything at all\n${INTERNAL_STATE_CLOSE}\n\n${REAL_REPLY}`, "clean"],
  ["reasoning without a state block is caught", `I should not promise it's coming.\n\n${REAL_REPLY}`, "clean"],
  ["a bare bullet list of titles is discarded", "  • Crowns brand\n  • Implants brand", "discard"],
  ["contamination after the reply is discarded, not trimmed", `${REAL_REPLY}\n\nTHIS REPLY CARRIES NO IMAGE, and none is being sent.`, "discard"],
];

for (const [name, input, expect] of shapes) {
  const out = stripInternalState(input);
  const ok =
    expect === "discard"
      ? out === null
      : out !== null && !containsInternalState(out) && out.includes("Implant Swiss");
  check(name, ok, `got ${out === null ? "null" : JSON.stringify(out.slice(0, 60))}`);
}

console.log("\n--- clean replies must be untouched ---");
const innocuous = [
  REAL_REPLY,
  "Here's what the process looks like: two visits, five days and then seven.",
  "Ten years is a long time. What was the hardest part of managing without them?",
  "We can share photos of previous cases whenever you'd like to see them.",
  "The team will review your case and follow up with an accurate quote.",
  "Our packages include airport transfers and a five-star hotel for the stay.",
];
for (const reply of innocuous) {
  check(
    `untouched: ${JSON.stringify(reply.slice(0, 44))}`,
    stripInternalState(reply) === reply && !containsInternalState(reply)
  );
}

console.log("\n--- property: real generated state blocks never survive ---");
const u = (c: string): ChatTurn => ({ role: "user", content: c });
const a = (c: string): ChatTurn => ({ role: "assistant", content: c });
const entries = [
  { title: "Crowns brand", content: "We use premium Straumann zirconia crowns for their natural appearance." },
  { title: "Implants brand", content: "We use Implant Swiss dental implants for their Swiss precision." },
  { title: "The package", content: "Includes VIP airport transfers and a five-star hotel stay in Istanbul." },
];
const histories: ChatTurn[][] = [
  [u("I want implants"), a("I can show you a before-and-after if you like."), u("yes")],
  [u("I want implants"), a("Would you like to see the crowns we use?"), u("how much?")],
  [u("I'm not sure yet, I need to think about it")],
  [u("my name is David"), a("Thanks David."), u("+44 7700 900123")],
  [u("hello"), a("What brings you in?"), u("hi")],
  [u("I've lost most of my upper teeth"), a("That's treatable."), u("how long does it take?")],
];
const decisions: MediaDecision[] = [
  { send: false, reason: "no-request" },
  { send: false, reason: "no-confident-match" },
  { send: false, reason: "already-shown" },
  { send: true, url: "https://x.test/a.jpg", type: "image/jpeg", title: "Crowns brand", alsoAvailable: [], reason: "accepted-offer" },
];

let generated = 0;
let survived = 0;
for (const history of histories) {
  for (const decision of decisions) {
    const instruction = buildMediaInstruction(decision);
    const block = buildConversationStateBlock(history, entries, instruction);
    if (!block) continue;
    generated++;
    for (const suffix of ["", `\n\n${REAL_REPLY}`]) {
      const contaminated = `${INTERNAL_STATE_OPEN}\n${block}\n${INTERNAL_STATE_CLOSE}${suffix}`;
      const out = stripInternalState(contaminated);
      if (out !== null && containsInternalState(out)) {
        survived++;
        console.log(`        LEAKED: ${JSON.stringify(out.slice(0, 90))}`);
      }
      // Unfenced too, since the model may echo the contents without the fence.
      const unfenced = `${block}${suffix}`;
      const out2 = stripInternalState(unfenced);
      if (out2 !== null && containsInternalState(out2)) {
        survived++;
        console.log(`        LEAKED (unfenced): ${JSON.stringify(out2.slice(0, 90))}`);
      }
    }
  }
}
check(`${generated} generated state blocks, none survives the guard`, survived === 0, `${survived} survived`);
check("the property test actually generated blocks", generated > 0);

console.log("\n--- structural: no sink can read the ungated reply ---");
const routeSrc = readFileSync(join(process.cwd(), "app/api/chat/route.ts"), "utf8");
// Everything the visitor or the record receives must read `reply`, the
// value produced by the guard — never rawReply, cleaned, or candidate.
const forbidden = [
  /content:\s*rawReply/,
  /content:\s*candidate/,
  /content:\s*cleaned/,
  /json\(\{\s*reply:\s*rawReply/,
  /json\(\{\s*reply:\s*candidate/,
  /json\(\{\s*reply:\s*cleaned/,
];
for (const pattern of forbidden) {
  check(`route never wires ${pattern.source}`, !pattern.test(routeSrc));
}
check(
  "the guard is applied before the reply is derived",
  /const cleaned = stripInternalState\(rawReply\);/.test(routeSrc) &&
    /const reply = containsInternalState\(candidate\) \? SAFE_FALLBACK : candidate;/.test(routeSrc)
);
check("the response returns the gated value", /return NextResponse\.json\(\{ reply, media \}\)/.test(routeSrc));
check("the stored row uses the gated value", /content:\s*reply,/.test(routeSrc));
check("the fallback exists and is non-empty", SAFE_FALLBACK.length > 20 && !containsInternalState(SAFE_FALLBACK));

console.log(bad ? `\n${bad} FAILING` : `\nall reply-guard tests passed`);
process.exit(bad ? 1 : 0);
