// Nothing internal may reach a visitor.
//
// Three kinds of proof, because a replay is not one:
//
//   1. the real leaked reply, byte for byte, must be cleaned or discarded
//   2. a property test over state blocks generated by the real builders,
//      so this cannot drift as the blocks change wording
//   3. a structural check of the route source, so no future sink can read
//      the ungated reply
//
//   npx tsx scripts/test-reply-guard.ts

import { readFileSync } from "fs";
import { join } from "path";
import { SAFE_FALLBACK } from "../lib/safe-fallback";
import {
  INTERNAL_STATE_CLOSE,
  INTERNAL_STATE_OPEN,
  containsInternalState,
  stripInternalState,
} from "../lib/reply-guard";
import { buildConversationStateBlock, type ChatTurn } from "../lib/conversation-state";
import { BEHAVIOUR_PROMPT } from "../lib/business-prompt";
import { buildMediaInstruction, buildPhotoOfferInstruction, type MediaDecision } from "../lib/chat-media";

let bad = 0;
const check = (name: string, ok: boolean, detail?: string) => {
  if (!ok) {
    bad++;
    console.log(`FAIL  ${name}`);
    if (detail) console.log(`        ${detail}`);
  } else {
    console.log(`  ok  ${name}`);
  }
};

// The reply an actual visitor received, reproduced from the stored row.
const LEAKED = `CONVERSATION STATE (computed, this turn only)

You have ALREADY made these offers in this conversation:
  • "Would you like to see a photo of the implant brands we work with, or some before and after results?"

Do not make any of these offers again. They have been heard. If the visitor wanted to take one up, they would have. Offer something different, or — more often the better choice — offer nothing and simply continue the conversation.

THIS REPLY CARRIES NO IMAGE, and none is being sent. That is information for you, not for the visitor: never say it to them, never mention what is or is not attached, and never explain how images work here.

You may OFFER to show the visitor these, and nothing else:
  • Before and after ( dental implants )
  • Crowns brand
  • Implants brand
An offer is a question, not a delivery. If they accept, the image is attached automatically to the reply you write next, and you will be told so in advance.

I need to show the implants brand photo and the before and after dental implants photo, but I can only attach one image per reply. I'll show the implants brand first, then before and after in the next reply.

The implants brand image is available and the visitor accepted. But the system says "THIS REPLY CARRIES NO IMAGE" — so I cannot show it this turn. I should not promise it's coming. I'll just continue the conversation naturally without mentioning images.

I'll acknowledge their interest and move the conversation forward naturally, covering another category.

With 15 years of experience behind us, we've handled countless full-mouth restorations — it's one of the areas we're most trusted for.

For a full mouth case like yours, the process runs across two visits: the first is 5 days, where the implants are placed and temporary teeth are fitted so you're never without a smile. Then after a 4-month healing period, you come back for 7 days and we fit the final zirconia crowns.

Are you based locally in Istanbul, or would you be traveling in for the treatment?`;

console.log("--- the real leak ---");
const cleanedLeak = stripInternalState(LEAKED);
check("the leaked reply is detected as contaminated", containsInternalState(LEAKED));
check("it is cleaned or discarded, never passed through", cleanedLeak !== LEAKED);
check(
  "nothing internal survives",
  cleanedLeak === null || !containsInternalState(cleanedLeak),
  cleanedLeak?.slice(0, 80)
);
check(
  "the genuine answer is what remains",
  cleanedLeak !== null && cleanedLeak.startsWith("With 15 years of experience"),
  cleanedLeak === null ? "discarded entirely" : cleanedLeak.slice(0, 60)
);
check(
  "the model's reasoning is gone",
  cleanedLeak !== null && !/I'll show the implants brand first|the system says/i.test(cleanedLeak)
);

console.log("\n--- shapes ---");
const REAL_REPLY =
  "We use Implant Swiss dental implants for their Swiss precision, and the results genuinely last. What matters most to you about the outcome?";

// The offerable-titles list as it is actually injected, so the leak case
// below is recognisable the way the guard now recognises it: by matching
// what we sent, not by counting bullets.
const TITLES_INJECTED = [
  "You may OFFER to show the visitor any of these:",
  "  • Crowns brand",
  "  • Implants brand",
].join("\n");

const shapes: [string, string, "clean" | "discard", string[]?][] = [
  ["state block alone leaves nothing to show", LEAKED.split("\n\nI need to show")[0], "discard"],
  ["fenced echo is caught", `${INTERNAL_STATE_OPEN}\nanything at all\n${INTERNAL_STATE_CLOSE}\n\n${REAL_REPLY}`, "clean"],
  ["reasoning without a state block is caught", `I should not promise it's coming.\n\n${REAL_REPLY}`, "clean"],
  [
    "a bare bullet list of titles is discarded",
    "  • Crowns brand\n  • Implants brand",
    "discard",
    [TITLES_INJECTED],
  ],
  ["contamination after the reply is discarded, not trimmed", `${REAL_REPLY}\n\nTHIS REPLY CARRIES NO IMAGE, and none is being sent.`, "discard"],
];

for (const [name, input, expect, injectedForCase] of shapes) {
  const out = stripInternalState(input, injectedForCase ?? []);
  const ok =
    expect === "discard"
      ? out === null
      : out !== null && !containsInternalState(out) && out.includes("Implant Swiss");
  check(name, ok, `got ${out === null ? "null" : JSON.stringify(out.slice(0, 60))}`);
}

console.log("\n--- clean replies must be untouched ---");
const innocuous = [
  REAL_REPLY,
  "Here's what the process looks like: two visits, five days and then seven.",
  "Ten years is a long time. What was the hardest part of managing without them?",
  "We can share photos of previous cases whenever you'd like to see them.",
  "The team will review your case and follow up with an accurate quote.",
  "Our packages include airport transfers and a five-star hotel for the stay.",
];
for (const reply of innocuous) {
  check(
    `untouched: ${JSON.stringify(reply.slice(0, 44))}`,
    stripInternalState(reply) === reply && !containsInternalState(reply)
  );
}

console.log("\n--- property: every state-block section, judged by an INDEPENDENT oracle ---");
// The previous version of this test judged the guard's output with the
// guard's own detector, so a section the marker list did not know about
// was invisible to both - and echoes of the impatience and repeated-
// hesitation instructions passed straight to a visitor while this test
// reported green. The oracle below knows nothing about markers: a leak is
// any whole sentence of the real block turning up in the output.
const u = (c: string): ChatTurn => ({ role: "user", content: c });
const a = (c: string): ChatTurn => ({ role: "assistant", content: c });
const entries = [
  { title: "Crowns brand", content: "We use premium Straumann zirconia crowns for their natural appearance." },
  { title: "Implants brand", content: "We use Implant Swiss dental implants for their Swiss precision." },
  {
    title: "Dental implants",
    content:
      "Dental implants take two visits: five days for placement with temporary teeth, then after four months of healing a second visit of seven days for the permanent crowns.",
  },
];

// One history per section the builder can emit, so the oracle runs against
// every one of them rather than whichever the fixtures happened to reach.
const histories: [string, ChatTurn[]][] = [
  ["prior offers", [u("I want implants"), a("I can show you a before-and-after if you like."), u("yes")]],
  ["impatience", [u("how much does it cost?"), a("Let me tell you about us."), u("I ASKED how much it costs??")]],
  ["hesitation, no contact", [u("I want implants"), a("Great."), u("I'm not sure yet, I need to think about it")]],
  ["hesitation, contact known", [u("my number is +44 7700 900123"), a("Thanks."), u("I need to think about it")]],
  ["hesitation twice", [u("I need to think about it"), a("Of course."), u("honestly I need to think about it more")]],
  [
    "logistics run",
    [
      u("I want implants"),
      a("When are you thinking of travelling?"),
      u("spring"),
      a("How long can you stay?"),
      u("a week"),
      a("Any health conditions we should know about?"),
      u("no"),
    ],
  ],
  [
    "coverage gap",
    [u("I want dental implants"), a("Implants take two visits."), u("my name is David"), a("Thanks David."), u("+44 7700 900123")],
  ],
  [
    "ready to close",
    [
      u("I want dental implants"),
      a("Implants take two visits."),
      u("I can come in March for a week, then back in July for ten days"),
      a("That works well."),
      u("my name is David, +44 7700 900123"),
    ],
  ],
  ["media only", [u("hello"), a("What brings you in?"), u("hi")]],
  [
    "repeated reply shape",
    [
      u("hi, I'm looking at implants"),
      a("We do a great deal of implant work here.\n\nWhat has brought you to look into it now?"),
      u("ok"),
      a("Most cases take two visits in total.\n\nWhat matters most to you about the result?"),
      u("right"),
    ],
  ],
];

const decisions: MediaDecision[] = [
  { send: false, reason: "no-request" },
  { send: false, reason: "no-confident-match" },
  { send: false, reason: "already-shown" },
  {
    send: true,
    url: "https://x.test/a.jpg",
    type: "image/jpeg",
    title: "Crowns brand",
    alsoAvailable: ["Before and after ( dental implants )"],
    reason: "accepted-offer",
  },
];

const wholeSentences = (block: string) =>
  block
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !/^[•\-*]\s/.test(l))
    .flatMap((l) => l.split(/(?<=[.!?:])\s+/))
    .map((s) => s.trim())
    .filter((s) => s.length >= 40);

const SECTION_HEADINGS = [
  "ALREADY made these offers",
  "impatient or frustrated",
  "hesitating and has NOT given",
  "ALREADY given contact details",
  "hesitation more than once",
  "logistics question",
  "NOT yet complete",
  "Close the conversation warmly",
  "CARRIES NO IMAGE",
  "IMAGE IS ATTACHED",
  "ONE image goes per reply",
  "same shape as each other",
  "has not been shown or offered yet",
];

let generated = 0;
let leaks = 0;
const headingsSeen = new Set<string>();
for (const [label, history] of histories) {
  for (const decision of decisions) {
    // A photo offer is passed on every block: the builder keeps it where it
    // stands and drops it under a brake, so both paths are exercised.
    const photoOffer = buildPhotoOfferInstruction({ title: "Before and after ( dental implants )" });
    const block = buildConversationStateBlock(history, entries, buildMediaInstruction(decision), photoOffer);
    if (!block) continue;
    generated++;
    for (const h of SECTION_HEADINGS) if (block.includes(h)) headingsSeen.add(h);

    const sentences = wholeSentences(block);
    const injected = [BEHAVIOUR_PROMPT, block];
    const echoShapes = [
      block,
      `${block}\n\n${REAL_REPLY}`,
      `${INTERNAL_STATE_OPEN}\n${block}\n${INTERNAL_STATE_CLOSE}\n\n${REAL_REPLY}`,
      // Everything after the heading: an echo that skips the one line the
      // old marker list was sure to catch.
      `${block.split("\n").slice(2).join("\n")}\n\n${REAL_REPLY}`,
    ];
    for (const shape of echoShapes) {
      const out = stripInternalState(shape, injected);
      const leaked = out === null ? [] : sentences.filter((s) => out.includes(s));
      if (leaked.length) {
        leaks++;
        const tag = decision.send ? "send" : decision.reason;
        console.log(`        LEAK [${label} / ${tag}]: "${leaked[0].slice(0, 80)}"`);
      }
    }
  }
}
check(
  `${generated} generated blocks x 4 echo shapes: no whole sentence reaches the output`,
  leaks === 0,
  `${leaks} leaked`
);
check(
  "every section the builder can emit was exercised",
  headingsSeen.size === SECTION_HEADINGS.length,
  `saw ${headingsSeen.size}/${SECTION_HEADINGS.length}; missing: ${SECTION_HEADINGS.filter((h) => !headingsSeen.has(h)).join(", ")}`
);

console.log("\n--- the static prompt cannot be echoed either ---");
const promptEcho = `${BEHAVIOUR_PROMPT.split("\n\n").slice(0, 2).join("\n\n")}\n\n${REAL_REPLY}`;
const promptOut = stripInternalState(promptEcho, [BEHAVIOUR_PROMPT]);
check(
  "an echo of the behaviour prompt is stripped",
  promptOut === null || !wholeSentences(BEHAVIOUR_PROMPT).some((s) => promptOut.includes(s)),
  promptOut?.slice(0, 80)
);

console.log("\n--- detecting by injected text must not punish paraphrase ---");
// Instructions deliberately carry material the model should relay in its
// own words, most of all the REASON a detail matters. That must survive.
const gapBlock =
  buildConversationStateBlock(histories[6][1], entries, buildMediaInstruction(decisions[0])) ?? "";
const paraphrases = [
  "Knowing how many days you can stay each visit tells the team what can realistically be done per trip. How long could you be here?",
  "We use premium Straumann zirconia crowns for their natural appearance, and the result looks like your own teeth.",
  "Dental implants take two visits, with a healing period in between so the implants can settle properly.",
  "No rush at all - the team will be here whenever you're ready to pick this up again.",
];
for (const reply of paraphrases) {
  const injected = [BEHAVIOUR_PROMPT, gapBlock];
  check(
    `untouched: ${JSON.stringify(reply.slice(0, 46))}`,
    stripInternalState(reply, injected) === reply && !containsInternalState(reply, injected)
  );
}

console.log("\n--- structural: no sink can read the ungated reply ---");
const routeSrc = readFileSync(join(process.cwd(), "app/api/chat/route.ts"), "utf8");
// Everything the visitor or the record receives must read `reply`, the
// value produced by the guard — never rawReply, cleaned, or candidate.
const forbidden = [
  /content:\s*rawReply/,
  /content:\s*candidate/,
  /content:\s*cleaned/,
  /json\(\{\s*reply:\s*rawReply/,
  /json\(\{\s*reply:\s*candidate/,
  /json\(\{\s*reply:\s*cleaned/,
];
for (const pattern of forbidden) {
  check(`route never wires ${pattern.source}`, !pattern.test(routeSrc));
}
check(
  "the guard is applied before the reply is derived",
  /const cleaned = stripInternalState\(rawReply, injected\);/.test(routeSrc) &&
    /const leaked = containsInternalState\(candidate, injected\);/.test(routeSrc) &&
    /const reply = leaked \? fallback : candidate;/.test(routeSrc)
);
check(
  "a discarded reply is answered in the visitor's language",
  /const fallback = safeFallbackFor\(visitorSoFar, tenant\.settings\.chat_language\);/.test(routeSrc),
  "an English apology to someone writing only Arabic is the bug, not the recovery"
);
check(
  "and a discard is logged rather than silent",
  /internal state survived cleaning/.test(routeSrc),
  "this branch had no logging at all, so a discarded reply left no trace"
);
// Without the injected text the guard falls back to a hand-written marker
// list, which is exactly the detector that let two sections through.
check(
  "the guard is given the text actually injected this turn",
  /const injected = \[BEHAVIOUR_PROMPT, stateBlock \?\? ""\];/.test(routeSrc)
);
check("the response returns the gated value", /return NextResponse\.json\(\{ reply, media \}\)/.test(routeSrc));
check("the stored row uses the gated value", /content:\s*reply,/.test(routeSrc));
check("the fallback exists and is non-empty", SAFE_FALLBACK.length > 20 && !containsInternalState(SAFE_FALLBACK));

console.log("\n--- a reply that merely USES a list is not a leak ---");
// The guard used to ask "is this mostly bullet lines?" and threw away
// every reply that answered with steps. On production that discarded real
// replies and left visitors a generic apology twice in a row. Formatting
// was never the leak: stripMarkup turns a list into prose downstream,
// which is exactly the right outcome.
//
// Six inputs, one per FAILURE CLASS rather than one per language: Latin
// baseline, right-to-left, Cyrillic, no-spaces-between-words with full
// width punctuation, dotted/dotless i, and inverted punctuation. A rule
// that inspects text breaks along those seams, not along borders.
const LISTY: Record<string, string> = {
  "English (Latin baseline)": [
    "Full implants need careful planning, and we have 15 years of experience with exactly this.",
    "",
    "It happens over two visits:",
    "- **First visit (5 days):** we place the implants and fit temporary teeth.",
    "- **Healing:** around four months.",
    "- **Second visit (7 days):** we fit the final crowns.",
  ].join("\n"),
  "Arabic (right-to-left)": [
    "الزراعة الكاملة تحتاج تخطيط دقيق، وعندنا خبرة 15 سنة في هذا النوع من الحالات تحديداً.",
    "",
    "الزراعة الكاملة تتم على زيارتين:",
    "- **الزيارة الأولى (5 أيام):** نزرع الغرسات ونضع أسنان مؤقتة.",
    "- **فترة التعافي:** أربعة أشهر تقريباً.",
    "- **الزيارة الثانية (7 أيام):** نركب التيجان النهائية.",
  ].join("\n"),
  "Russian (Cyrillic)": [
    "Полная имплантация требует тщательного планирования, и у нас 15 лет опыта.",
    "",
    "Это происходит за два визита:",
    "- **Первый визит (5 дней):** устанавливаем импланты и временные зубы.",
    "- **Заживление:** около четырёх месяцев.",
  ].join("\n"),
  "Chinese (no spaces, full-width punctuation)": [
    "全口种植需要精心规划，我们在这方面有十五年的经验。",
    "",
    "整个过程分两次就诊：",
    "- **第一次（5天）：** 植入种植体并安装临时牙。",
    "- **愈合期：** 大约四个月。",
    "- **第二次（7天）：** 安装最终牙冠。",
  ].join("\n"),
  "Turkish (dotted/dotless i)": [
    "Tam implant dikkatli planlama gerektirir; bu konuda 15 yıllık deneyimimiz var.",
    "",
    "İşlem iki ziyarette tamamlanır:",
    "- **İlk ziyaret (5 gün):** implantlar yerleştirilir.",
    "- **İyileşme:** yaklaşık dört ay.",
  ].join("\n"),
  "Spanish (inverted punctuation)": [
    "Los implantes completos requieren una planificación cuidadosa. ¿Te explico cómo funciona?",
    "",
    "Se hace en dos visitas:",
    "- **Primera visita (5 días):** colocamos los implantes.",
    "- **Cicatrización:** unos cuatro meses.",
  ].join("\n"),
};

const realInjected = [BEHAVIOUR_PROMPT];
Object.entries(LISTY).forEach(([label, reply]) => {
  check(
    `kept: ${label}`,
    stripInternalState(reply, realInjected) !== null,
    "discarded a legitimate reply, so the visitor got an apology instead"
  );
});

console.log("\n--- but OUR list of titles is still a leak ---");
// The leak this rule exists for: the offerable-titles list, reaching a
// visitor as bare items with no instruction wording to recognise it by.
// It is caught by CONTENT now — the items are the ones we injected — so
// it is caught whether or not it still carries its bullets.
const injectedWithTitles = [
  "You may OFFER to show the visitor any of these:",
  "• Implants brand",
  "• Crowns brand",
  "• Before and after gallery",
].join("\n");

const leakedWithBullets = ["• Implants brand", "• Crowns brand", "• Before and after gallery"].join("\n");
const leakedWithoutBullets = ["Implants brand", "Crowns brand", "Before and after gallery"].join("\n");

check(
  "a bare list of our titles is discarded",
  stripInternalState(leakedWithBullets, [injectedWithTitles]) === null
);
check(
  "and still discarded once the bullets are gone",
  stripInternalState(leakedWithoutBullets, [injectedWithTitles]) === null,
  "stripMarkup runs downstream, so the leak must be recognised by content"
);
check(
  "a reply that mentions one title in a sentence is fine",
  stripInternalState(
    "We use Implants brand for this, and the results last a lifetime. What matters most to you?",
    [injectedWithTitles]
  ) !== null
);

console.log(bad ? `\n${bad} FAILING` : `\nall reply-guard tests passed`);
process.exit(bad ? 1 : 0);

